// components/glt-app/src/app/edit/edit.component.ts
import {Component, OnDestroy} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {ConfigService} from '../services/config.service';

import {glt, CJSON} from '../../vendor';
declare const window;

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.css']
})
export class EditComponent implements OnDestroy {
  config;

  route;
  view = {data: 'graph', shader: 'all', type: 'three', vars: 2, multi: false};
  display = {};

  syntax;
  syntaxJson;
  graph;
  graphJson;
  tree;
  treeJson;
  running = false;
  updateCounter = 0;

  time = -1;
  compiled: any = {};
  histogram = null;
  renderedPartials: any = {};

  constructor(config: ConfigService, route: ActivatedRoute) {
    this.config = config;
    this.route = route;

    if (this.route.params.value.json) {
      this.config.original = JSON.parse(this.route.params.value.json);
      this.config.source = glt.deep(this.config.original);
    }

    this.graph = this.config.source;
  }

  indexFn = (i) => i;

  ngOnDestroy() {
    this.stop();
  }

  onCompiled(compiled) {
    Object.assign(this.compiled, compiled);
    this.sourceChanged();
  }

  reset() {
    this.config.source = glt.deep(this.config.original);
    this.graph = this.config.source;
  }

  change(v) {
    glt.valueToGraph(this.compiled.ids, v);
    this.graphJson = CJSON(this.graph);
    this.config.source = this.graph;
    this.updateCounter++;
  }

  sourceChanged() {
    this.tree = this.compiled.tree;
    this.graphJson = CJSON(this.graph);
    this.treeJson = CJSON(this.tree);
    this.graphChanged();
  }

  graphChanged() {
    this.treeChanged();
  }

  treeChanged() {
    this.syntaxJson = CJSON(this.compiled.syntax);

    for (const key in this.compiled.uniforms) {
      if (this.compiled.uniforms.hasOwnProperty(key)) {
        this.compiled.uniforms[key].animate = this.compiled.uniforms[key].value.length ? [] : true;
      }
    }

    this.updateDisplay();
  }

  updateDisplay() {
    const shaders = {
      three: glt.getShaderThree,
      glsl: glt.getShaderGlslSandbox,
      toy: glt.getShaderShadertoy,
    };
    this.display = glt.formatShader(
      this.tree,
      parseInt(this.view.vars.toString(), 10),
      this.view.multi,
      this.compiled.uniforms,
      shaders[this.view.type]
    );
  }

  randomize() {
    this.treeJson = CJSON(glt.randomTree2());
    this.treeChanged();
  }

  loop() {
    if (this.running) {
      glt.step(this.compiled.uniforms);
      this.updateCounter++;
      window.requestAnimationFrame(() => this.loop());
    }
  }

  start() {
    if (!this.running) {
      this.running = true;
      this.loop();
    } else {
      this.stop();
    }
  }

  stop() {
    this.running = false;
  }
}

<div fxFlexFill fxFlex fxLayout="column" fxLayout.gt-md="row" fxLayoutAlign="stretch">
  <md-input-container fxHide>
    <textarea mdInput></textarea>
  </md-input-container>
  <md-tab-group fxFlex fxLayout="column" dynamicHeight class="mat-elevation-z2"
                style="z-index: 5000; background-color: #fafafa">
    <md-tab label="Components" fxFlex>
      <div fxFlex fxLayoutWrap fxLayout="row" fxLayoutAlign="start start" class="overflow-y padding">
        <div *ngIf="compiled"
             fxHide
             appRender
             [renderPreCompiled]="compiled"
             [renderSize]="config.partialSize"
             [renderUpdate]="updateCounter"
             renderMode="1"
             [renderOffScreen]="renderedPartials"
             renderPartials="true"
             style="z-index: 4000; background-color: #fafafa"></div>
        <div *ngFor="let item of compiled.ids | keys" class="padding mat-elevation-z1">
          <span>{{item.key}} &mdash; {{item.value[0]}}</span>
          <div></div>
        </div>
      </div>
    </md-tab>
    <md-tab label="Uniforms" fxFlex>
      <div fxFlex fxLayoutWrap fxLayout="row" fxLayoutAlign="start start" class="overflow-y padding">
        <div *ngFor="let item of compiled.uniforms | keys" fxFlex="375px" class="padding">
          <h4>{{item.key}}</h4>
          <div *ngIf="!item.value.value.length">
            <md-slider thumbLabel
                       type="range"
                       (change)="change(item.value)"
                       [(ngModel)]="item.value.value"
                       #ctrl="ngModel"
                       [min]="item.value.proto[3][0]"
                       [max]="item.value.proto[3][1]"
                       step="0.01"></md-slider>
            <md-input-container>
              <input mdInput
                     type="number"
                     (change)="change(item.value)"
                     [(ngModel)]="item.value.value">
            </md-input-container>
            <md-checkbox type="checkbox"
                         [(ngModel)]="item.value.animate"></md-checkbox>
          </div>
          <div *ngIf="item.value.value.length">
            <div *ngFor="let sub of item.value.value; trackBy:indexFn; let i = index">
              <md-slider thumbLabel
                         type="range"
                         (change)="change(item.value)"
                         [(ngModel)]="item.value.value[i]"
                         #ctrl="ngModel"
                         [min]="item.value.proto[3][0]"
                         [max]="item.value.proto[3][1]"
                         step="0.01"></md-slider>
              <md-input-container>
                <input mdInput
                       type="number"
                       (change)="change(item.value)"
                       [(ngModel)]="item.value.value[i]">
              </md-input-container>
              <md-checkbox type="checkbox"
                           [(ngModel)]="item.value.animate[i]"></md-checkbox>
            </div>
          </div>
        </div>
      </div>
    </md-tab>
    <md-tab label="Data" fxFlex fxLayout="column">
      <md-radio-group class="md-radio-group" [(ngModel)]="view.data">
        <md-radio-button class="md-radio-button" value="graph">Graph</md-radio-button>
        <md-radio-button class="md-radio-button" value="tree">Tree</md-radio-button>
        <md-radio-button class="md-radio-button" value="syntax">Syntax</md-radio-button>
      </md-radio-group>
      <textarea *ngIf="view.data === 'graph'" fxFlex mdInput [(ngModel)]="graphJson"
                (change)="graphChanged()"
                autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"></textarea>
      <textarea *ngIf="view.data === 'tree'" fxFlex mdInput [(ngModel)]="treeJson"
                (change)="treeChanged()"
                autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"></textarea>
      <textarea *ngIf="view.data === 'syntax'" fxFlex mdInput [(ngModel)]="syntaxJson"
                autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"></textarea>
    </md-tab>
    <md-tab label="Shader">
      <div fxLayout="row">
        <md-radio-group class="md-radio-group" [(ngModel)]="view.shader">
          <md-radio-button class="md-radio-button" value="all">All</md-radio-button>
          <md-radio-button class="md-radio-button" value="color">Color</md-radio-button>
          <md-radio-button class="md-radio-button" value="functions">Functions</md-radio-button>
          <md-radio-button class="md-radio-button" value="variables">Variables</md-radio-button>
        </md-radio-group>
        <md-radio-group class="md-radio-group" [(ngModel)]="view.type" (change)="updateDisplay()">
          <md-radio-button class="md-radio-button" value="three">Three.js</md-radio-button>
          <md-radio-button class="md-radio-button" value="glsl">glslsandbox.com</md-radio-button>
          <md-radio-button class="md-radio-button" value="toy">shadertoy.com</md-radio-button>
        </md-radio-group>
        <md-radio-group class="md-radio-group" [(ngModel)]="view.vars" (change)="updateDisplay()">
          <md-radio-button class="md-radio-button" value="2">Define</md-radio-button>
          <md-radio-button class="md-radio-button" value="1">Uniforms</md-radio-button>
          <md-radio-button class="md-radio-button" value="0">Inline</md-radio-button>
        </md-radio-group>
        <div class="padding-2">
          <md-checkbox [(ngModel)]="view.multi" (change)="updateDisplay()">Multi line
          </md-checkbox>
        </div>
      </div>
      <textarea *ngIf="view.shader === 'color'" fxFlex mdInput [(ngModel)]="display.color" autocomplete="off"
                autocorrect="off" autocapitalize="off" spellcheck="false"></textarea>
      <textarea *ngIf="view.shader === 'functions'" fxFlex mdInput [(ngModel)]="display.functions"
                class="pre" autocomplete="off" autocorrect="off" autocapitalize="off"
                spellcheck="false"></textarea>
      <textarea *ngIf="view.shader === 'variables'" fxFlex mdInput [(ngModel)]="display.variables"
                class="pre" autocomplete="off" autocorrect="off" autocapitalize="off"
                spellcheck="false"></textarea>
      <textarea *ngIf="view.shader === 'all'" fxFlex mdInput [(ngModel)]="display.all" class="pre"
                autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"></textarea>
    </md-tab>
  </md-tab-group>
  <div fxLayout="column" style="z-index: 3000" class="bg">
    <div [appRender]="graph"
         [renderSize]="config.editSize"
         (renderTime)="time = $event"
         [renderUpdate]="updateCounter"
         renderHistogram="true"
         (renderHistogramEvent)="histogram = $event"
         [renderHistogramBins]="config.histogramBin"
         renderFull="true"
         renderDirect="true"
         renderMode="1"
         (renderCompiled)="onCompiled($event)"
         class="divider"
         style="background-color: #888; z-index: 4000"
         [style.width.px]="config.editSize[0]"
         [style.height.px]="config.editSize[1]"
         #renderMain></div>
    <md-toolbar class="divider" style="z-index: 2000">
      <button md-icon-button (click)="start()">
        <md-icon [textContent]="running ? 'pause' : 'play_arrow'"></md-icon>
      </button>
      <button md-icon-button (click)="reset()">
        <md-icon>undo</md-icon>
      </button>
      <button md-icon-button (click)="reset()">
        <md-icon>redo</md-icon>
      </button>
      <button md-icon-button (click)="renderMain.click($event)">
        <md-icon>fullscreen</md-icon>
      </button>
      <span fxFlex></span>
      <div *ngIf="config.editSize[0] > 256" class="mono padding">
        <span *ngIf="time < 0">&mdash;</span>
        <span *ngIf="time >= 0">{{time | number}}</span> ms
      </div>
    </md-toolbar>
    <div
      *ngIf="histogram"
      [appHistogram]="histogram"
      [histogramSize]="[config.editSize[0], config.histogramSize]"
      [histogramOptionsDark]="config.histogramDark"
      [histogramOptionsCurve]="config.histogramCurve"
      [histogramOptionsMid]="true"
      class="divider"></div>
  </div>
</div>

// components/glt-vue/src/components/Edit.vue
<template>
  <div class="main-content" style="height: 100%">
    <md-layout md-row style="height: 100%">
      <md-layout md-column>
        <md-tabs class="md-transparent" :md-dynamic-height="false" v-on:change="tab = $event">
          <md-tab id="tab-1" md-label="Components"></md-tab>
          <!--<md-tab id="tab-2" md-label="Uniforms">-->
          <!--<div>Uniforms</div>-->
          <!--</md-tab>-->
          <md-tab id="tab-3" md-label="Data"></md-tab>
          <md-tab id="tab-4" md-label="Shader"></md-tab>
        </md-tabs>

        <md-layout v-if="tab === 0 && compiled" md-column>
          <div class="scroll-y padding">
            <md-layout md-row md-gutter>
              <div v-for="(item, index) in compiled.ids" class="margin">
                <md-card style="min-width: 256px">
                  <span class="md-title">{{item[0]}}</span>
                  <div v-for="(v, i) in compiled.uniforms" class="margin" v-if="v.id == index">
                    <span class="md-subheading">{{v.proto[1]}}</span>
                    <md-layout v-if="!v.value.length" class="params">
                      <div>
                        <slider v-model="v.value" v-on:input="v.value = $event, updateParam(v)" :min="v.proto[3][0]" :max="v.proto[3][1]" :step="0.01"></slider>
                      </div>
                      <div>
                        <md-input-container>
                          <md-input v-model.number="v.value" type="number"></md-input>
                        </md-input-container>
                      </div>
                    </md-layout>
                    <md-layout v-else v-for="(w, u) in v.value" :key="u" class="params">
                      <div>
                        <slider v-model="v.value[u]" v-on:input="v.value[u] = $event, updateParam(v)" :min="v.proto[3][0]" :max="v.proto[3][1]" :step="0.01"></slider>
                      </div>
                      <div>
                        <md-input-container>
                          <md-input v-model.number="v.value[u]" type="number"></md-input>
                        </md-input-container>
                      </div>
                    </md-layout>
                  </div>
                </md-card>
              </div>
            </md-layout>
          </div>
        </md-layout>

        <md-layout v-else-if="tab === 1" md-column class="padding-side">
          <md-layout md-row md-gutter md-align="start" class="no-flex padding-top">
            <md-card class="md-whiteframe-1dp">
              <div>
                <md-radio
                  v-for="(item, index) in dataViews" :key="index"
                  v-model="dataView"
                  v-on:change="dataView = $event, dataEdit = toCJSON(data[dataView])"
                  class="md-primary"
                  :md-value="item"
                  :name="'data-view-' + index"
                  :id="'data-view-' + index">
                  {{item}}
                </md-radio>
              </div>
            </md-card>
          </md-layout>
          <textarea class="mono pre padding-bottom scroll-y" style="flex: 1; width: 100%" v-model="dataEdit"
                    :disabled="dataView !== 'Graph'"
                    v-on:change="dataChanged($event)"
                    v-on:keyup="dataChanged($event)"></textarea>
        </md-layout>

        <md-layout v-else-if="tab === 2" md-column class="padding-side">
          <md-layout md-row md-gutter md-align="start" class="no-flex padding-top">
            <md-card class="md-whiteframe-1dp">
              <div>
                <md-radio
                  v-on:change="shaderView = $event, updateShader()"
                  v-for="(item, index) in shaderViews" :key="index"
                  v-model="shaderView"
                  class="md-primary"
                  :md-value="item"
                  :name="'shader-view-' + index"
                  :id="'shader-view-' + index">
                  {{item}}


                </md-radio>
              </div>
            </md-card>
            <md-card class="md-whiteframe-1dp">
              <div>
                <md-radio
                  v-on:change="shaderTarget = $event, updateShader()"
                  v-for="(item, index) in shaderTargets" :key="index"
                  v-model="shaderTarget"
                  class="md-primary"
                  :md-value="item"
                  :name="'shader-target-' + index"
                  :id="'shader-target-' + index">{{item}}


                </md-radio>
              </div>
            </md-card>
            <md-card class="md-whiteframe-1dp">
              <div>
                <md-radio
                  v-on:change="shaderType = $event, updateShader()"
                  v-for="(item, index) in shaderTypes" :key="index"
                  v-model="shaderType"
                  class="md-primary"
                  :md-value="item"
                  :name="'shader-type-' + index"
                  :id="'shader-type-' + index">{{item}}
                </md-radio>
              </div>
            </md-card>
            <md-card class="md-whiteframe-1dp">
              <md-checkbox
                v-on:change="multiLine = $event, updateShader()"
                id="shader-multi-line"
                name="shader-multi-line"
                v-model="multiLine"
                class="md-primary">Multi line
              </md-checkbox>
            </md-card>
          </md-layout>

          <textarea class="mono pre padding-bottom scroll-y" style="flex: 1; width: 100%" v-model="shader"
                    disabled></textarea>
        </md-layout>

      </md-layout>
      <md-layout md-column class="no-flex">
        <draw :recipe="recipe"
              :size="config.editSize"
              direct="true"
              histogram="true"
              v-on:compiled="updateData($event)"
              v-on:histogram="updateHistogram = $event"
              :style="{width: config.editSize[0] + 'px', height: config.editSize[1] + 'px'}"
              class="md-whiteframe-1dp"></draw>
        <histogram
          :render="updateHistogram"
          :dark="config.histogramDark"
          :curve="config.histogramCurve"
          :size="[config.editSize[0], config.editSize[0] / 2]"
          class="md-whiteframe-1dp"></histogram>
      </md-layout>
    </md-layout>
  </div>
</template>

<script>
  import draw from './Draw'
  import histogram from './Histogram'
  import config from '../services/config'
  import slider from './Slider'
//  import Vue from 'vue'

  export default {
    name: 'edit',
    components: {
      draw: draw,
      histogram: histogram,
      slider: slider
    },
    data () {
      const recipe = this.$route.params.json ? JSON.parse(this.$route.params.json) : glt.samplesDemo[0]
      return {
        tab: 0,
        recipe: recipe,
        config: config,
        dataView: 'Graph',
        dataViews: ['Graph', 'Tree', 'Syntax'],
        shaderView: 'All',
        shaderViews: ['All', 'Color', 'Functions', 'Variables'],
        shaderTarget: 'Three.js',
        shaderTargets: ['Three.js', 'glslsandbox.com', 'shadertoy.com'],
        shaderType: 'Define',
        shaderTypes: ['Define', 'Uniforms', 'Inline'],
        multiLine: false,
        shader: this.getShader(recipe, 'Three.js', 'Define', false)['all'],
        data: {
          Graph: recipe
        },
        dataEdit: this.toCJSON(recipe),
        updateHistogram: 0,
        compiled: null
      }
    },
    methods: {
      toCJSON (o) {
        return CJSON(o)
      },
      updateParam (v) {
        this.valueToGraph(this.compiled.ids, v)
        this.recipe = Object.assign({}, this.compiled.graph)
      },
      valueToGraph (ids, value) {
        glt.valueToGraph(ids, value)
//        Vue.set(ids[value.id], value.index, value.value)
      },
      dataChanged (e) {
        if (this.dataView === 'Graph') {
          try {
            let o = JSON.parse(e.target.value)
            this.recipe = o
          } catch (ign) {}
        }
      },
      updateData (compiled) {
        this.data = {
          Graph: compiled.graph,
          Tree: compiled.tree,
          Syntax: compiled.syntax
        }
        this.compiled = compiled
        this.dataEdit = this.toCJSON(this.data[this.dataView])
      },
      updateShader () {
        this.shader = this.getShader(this.recipe, this.shaderTarget, this.shaderType, this.multiLine)[this.shaderView.toLowerCase()]
      },
      getShader (recipe, shaderTarget, shaderType, multiLine) {
        const shaders = {
          'Three.js': glt.getShaderThree,
          'glslsandbox.com': glt.getShaderGlslSandbox,
          'shadertoy.com': glt.getShaderShadertoy
        }

        const vars = {
          Define: 2,
          Uniforms: 1,
          Inline: 0
        }

        return glt.formatShader(
          recipe,
          vars[shaderType],
          multiLine,
          {},
          shaders[shaderTarget]
        )
      }
    }
  }
</script>

<style scoped>
  .mono {
    font-family: "Roboto Mono", monospace;
    font-size: 14px;
    line-height: 18px;
    font-weight: 500;
    letter-spacing: 0;
  }

  .pre {
    white-space: pre-wrap;
  }

  .no-flex {
    flex: initial !important;
  }

  .md-card.md-whiteframe-1dp, textarea {
    padding-left: 16px;
    padding-right: 8px;
    margin-right: 16px;
    margin-bottom: 16px;
    border: 1px solid rgba(0, 0, 0, .12);
    box-shadow: none;
  }

  textarea {
    resize: none;
    border-radius: 2px;
    margin: 0;
    padding: 0;
  }

  textarea:focus {
    outline: none;
  }

  textarea:disabled {
    background-color: transparent;
    border: none;
  }

  .md-tabs .md-tab {
    padding: 0;
  }

  .padding {
    padding: 8px;
  }

  .md-title {
    color: rgba(0, 0, 0, .87) !important;
    padding: 8px 16px;
  }

  .margin {
    margin: 8px;
  }

  .padding-top {
    margin: 16px 0 0 0;
  }

  .padding-bottom {
    margin-bottom: 16px;
  }

  .padding-side {
    padding: 0 16px;
  }

  .scroll-y {
    overflow-y: auto;
  }

  .v-range-slider {
    margin-top: 10px;
    margin-right: 8px;
    width: 160px;
    margin-bottom: -8px;
  }

  .md-input-container {
    width: 60px;
    min-height: 0;
    margin: -4px 0 4px;
    padding-top: 0;
  }

  .md-subheading {
    margin-bottom: -16px;
    padding-left: 8px;
    display: block;
  }

  .params {
    padding: 0 6px;
  }
</style>
