// components/glt-app/src/app/list/list.component.ts
import {Component} from '@angular/core';
import {ConfigService} from '../services/config.service';
import {ActivatedRoute} from '@angular/router';

import {glt} from '../../vendor';

declare const window;

@Component({
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.css']
})
export class ListComponent {
  config: any;
  recipes: any = [];
  times: any = [];
  code: any;
  generator: any;

  constructor(config: ConfigService, route: ActivatedRoute) {
    this.config = config;
    this.code = route.routeConfig.data['code'];
    const that = this;
    this.config.fab = route.routeConfig.data['refresh'] ? () => that.refresh() : null;

    const _list = glt[route.routeConfig.data['list']];
    const _generator = this.generator = glt[route.routeConfig.data['generator']];
    let list;

    if (_list) {
      list = _list.call ? _list() : glt.deep(_list);
    }

    while (list ? list.length : this.recipes.length < this.config.randomItems) {
      this.times.push({value: -1});
      if (list) {
        this.recipes.push(list.shift());
      } else {
        this.recipes.push(_generator());
      }
    }
  }

  refresh() {
    this.recipes.forEach((r, i) => {
      this.recipes[i] = this.generator();
      this.times[i].value = -1;
    });
  }

  ngOnDestroy() {
    this.config.fab = null;
  }

  toJson(value) {
    return JSON.stringify(value)
  }

  spacers(w) {
    const n = Math.ceil(Math.max(window.screen.width, window.screen.height) / w);
    const ret = [];

    for (let i = 0; i < n; i++) {
      ret.push(i);
    }

    return ret;
  }
}

<div fxFlexFill fxFlex fxLayout="row" fxLayoutAlign="space-around start" fxLayoutWrap class="canvas-list">
  <a [routerLink]="['/edit/', toJson(item)]"
     *ngFor="let item of recipes; let i = index;"
     fxLayout="column"
     fxLayoutAlign="center center"
     [ngClass]="{titled: item.title, subtitled: config.show.time || config.show.code}"
     class="canvas-wrap mat-elevation-z2">
    <div fxFlexFill>
      <div class="card-title" *ngIf="item.title">{{item.title}}</div>
    </div>
    <div [appRender]="item"
         [renderSize]="config.thumbnailSize"
         [renderQuality]="config.thumbnailQuality"
         [renderTime]="times[i]"
         [renderPartials]="config.show.partials"
         renderMode="1"
         [class.mat-elevation-z1]="code"
         fxLayout="column">
    </div>
    <div *ngIf="config.show.time"
         fxFlexAlign="end"
         class="mono time">
      <span *ngIf="times[i].value < 0">&mdash;</span>
      <span *ngIf="times[i].value >= 0">{{times[i].value | number}}</span> ms
    </div>
    <div *ngIf="config.show.code" fxFlexAlign="stretch">
      <div class="padding pre mono">{{item | cjson:1:(config.thumbnailSize[0]/8)}}</div>
    </div>
  </a>
  <div *ngFor="let spacer of spacers(config.thumbnailSize[0] + 16)" [style.width.px]="config.thumbnailSize[0] + 16"></div>
</div>

// components/glt-vue/src/components/List.vue
<template>
  <div class="main-content">
    <md-layout md-gutter class="md-wrap">
      <router-link v-for="(item, index) in recipes" :key="id + '-' + index"
                   :to="{ name: 'Edit', params: { json: toJSON(item) }}">
        <md-card>
          <span v-if="item.title"
                v-bind:class="[config.thumbnailSize[0] > 128 ? 'md-title' : 'md-body-2']">{{item.title}}</span>
          <md-layout md-align="center">
            <draw :recipe="item"
                  :size="config.thumbnailSize"
                  :partials="config.partials"
                  v-on:time="onTime($event, index)"
                  :style="{width: config.thumbnailSize[0] + 'px'}"></draw>
          </md-layout>
          <span v-if="config.time" class="mono right">{{(times[index] > -1) ? times[index] : '&mdash;'}} ms</span>
          <span v-if="config.code" class="pre mono">{{toCJSON(item.data)}}</span>
        </md-card>
      </router-link>
      <div class="spacer" v-for="item in getSpacers(config.thumbnailSize[0])"
           :style="{width: config.thumbnailSize[0] + 'px'}"></div>
    </md-layout>
  </div>
</template>

<script>
  import draw from '@/components/Draw'
  import config from '../services/config'
  import Vue from 'vue'

  let ID = 1

  export default {
    name: 'list',
    components: {
      draw: draw
    },
    watch: {
      $route: function () {
        const data = this.getData()
        this.recipes = data.recipes
        this.times = data.times
        this.id = data.id
      }
    },
    data () {
      return this.getData()
    },
    methods: {
      onTime: function (v, i) {
        Vue.set(this.times, i, v)
      },
      refresh: function () {
        Object.assign(this, this.getData())
      },
      toCJSON: function (o) {
        return CJSON(o, {indent: 1, maxLength: 32})
      },
      toJSON: function (o) {
        return JSON.stringify(o)
      },
      getSpacers: function (w) {
        const n = Math.ceil(Math.max(window.screen.width, window.screen.height) / w)
        const ret = []

        for (let i = 0; i < n; i++) {
          ret.push(i)
        }

        return ret
      },
      getData: function () {
        const recipes = []
        const times = []
        const _list = glt[this.$route.meta.list]
        const _generator = this.generator = glt[this.$route.meta.generator]
        let list

        if (_list) {
          list = _list.call ? _list() : glt.deep(_list)
        }

        while (list ? list.length : recipes.length < 78) {
          times.push(-1)
          if (list) {
            recipes.push(list.shift())
          } else {
            recipes.push(_generator())
          }
        }

        return {
          recipes: recipes,
          times: times,
          id: this.$route.meta.generator ? ID++ : this.$route.meta.list,
          config: config
        }
      }
    }
  }
</script>

<style scoped>
  .md-wrap {
    margin: 6px 6px;
    justify-content: space-around;
    align-items: flex-start;
  }

  .md-wrap > * {
    display: flex;
    margin: 6px 6px;
  }

  .spacer {
    margin-top: 0;
    margin-bottom: 0;
  }

  canvas {
    max-width: inherit;
    display: block;
  }

  .md-body-2 {
    padding: 4px 8px;
  }

  .md-card .md-title {
    padding: 8px 16px;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  .right {
    text-align: right;
    padding-right: 4px;
  }

  .mono {
    font-family: "Roboto Mono", monospace;
    font-size: 12px;
    line-height: 18px;
    font-weight: 500;
    letter-spacing: 0;
  }

  .pre {
    white-space: pre;
    font-size: 14px;
    line-height: 18px;
    font-weight: 500;
    letter-spacing: 0;
    padding: 8px 8px 8px 8px;
  }

  .md-theme-default a:not(.md-button):hover {
    text-decoration: none;
    color: inherit;
  }

  .md-theme-default a:not(.md-button) {
    color: inherit;
  }
</style>
